layout_spectrum: 1
typography_spectrum: 0.606383
color:
  saturation: 0
  lightness: 0
  brandStrength: 1
  brandColors:
    - '#040404'
    - '#3F3F3F'
    - '#676767'
    - '#DFDFDF'
    - '#A3A3A3'
  rhythmicContrast: 0
name: 'Maciej Łukaszuk '
