favicon: null
name: Maciej Łukaszuk cello
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0
  brandStrength: 1
  rhythmicContrast: 0
  brandColors:
    - '#040404'
    - '#3F3F3F'
    - '#676767'
    - '#DFDFDF'
    - '#A3A3A3'
  lightness: 0
typography_spectrum: 1
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.1021277
analytics:
  twitter: null
  google: null
  facebook: null
